// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOuQwbQubzhivyQbrVDhOJcc7sbiLVmeA',
    appId: '1:337041228734:web:a941daadd7208ff25fafef',
    messagingSenderId: '337041228734',
    projectId: 'minimal-social-app-72bea',
    authDomain: 'minimal-social-app-72bea.firebaseapp.com',
    storageBucket: 'minimal-social-app-72bea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx10m1EgQUCnmFaEbKN0nsZPZ7mxYk1ic',
    appId: '1:337041228734:android:81bde45005f2f36d5fafef',
    messagingSenderId: '337041228734',
    projectId: 'minimal-social-app-72bea',
    storageBucket: 'minimal-social-app-72bea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA0OiBwWTz3ZOx_E1RJ-UCYCjarVI6PDA',
    appId: '1:337041228734:ios:9a559dcdbad5f1025fafef',
    messagingSenderId: '337041228734',
    projectId: 'minimal-social-app-72bea',
    storageBucket: 'minimal-social-app-72bea.appspot.com',
    iosBundleId: 'com.pawan.socialmediaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA0OiBwWTz3ZOx_E1RJ-UCYCjarVI6PDA',
    appId: '1:337041228734:ios:6fc12f773e5edfce5fafef',
    messagingSenderId: '337041228734',
    projectId: 'minimal-social-app-72bea',
    storageBucket: 'minimal-social-app-72bea.appspot.com',
    iosBundleId: 'com.pawan.socialmediaapp.RunnerTests',
  );
}
